#!/bin/bash
# Generate PR body for Go version updates
# Usage: generate-pr-body.sh [new_files] [modified_files]

NEW_FILES="${1:-0}"
MODIFIED_FILES="${2:-0}"

# Generate the PR body
cat <<'EOF'
## Summary
This automated PR updates the Go version SHA256 checksums to include the latest stable releases from go.dev.

## Changes
- Updated checksum files in `vars/versions/`
- Generated by running `generate_golang_checksum_files.py`
EOF

# Add file statistics if provided
if [ "$NEW_FILES" -gt 0 ] || [ "$MODIFIED_FILES" -gt 0 ]; then
  echo ""
  echo "### Files changed"
  [ "$NEW_FILES" -gt 0 ] && echo "- New version files: $NEW_FILES"
  [ "$MODIFIED_FILES" -gt 0 ] && echo "- Updated version files: $MODIFIED_FILES"
fi

cat <<'EOF'

## Testing
The CI pipeline will validate these changes across all supported platforms and architectures.

🤖 Generated by GitHub Actions
EOF
