#!/bin/bash
# Generate a conventional commit message for Go version updates
# Usage: generate-commit-message.sh <commit_type> <new_files> <modified_files>

COMMIT_TYPE="${1:-fix}"
NEW_FILES="${2:-0}"
MODIFIED_FILES="${3:-0}"

# Determine the commit message based on type
if [ "$COMMIT_TYPE" = "feat" ]; then
  COMMIT_MSG="add Go version checksums"
else
  COMMIT_MSG="update Go version checksums"
fi

# Generate the full commit message
cat <<EOF
${COMMIT_TYPE}: ${COMMIT_MSG}

This automated update includes the latest Go version SHA256 checksums from go.dev.

- New version files: ${NEW_FILES}
- Updated version files: ${MODIFIED_FILES}

🤖 Generated by GitHub Actions
EOF
